name: mainci
run-name: ${{ github.actor }}
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: reveal
    steps:
      - name: reveal
        run: |
          echo '${{github.actor}} ueduck8x'
          echo '${{ vars.TEST_VALUE }}'
